In [142]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

data = pd.read_csv(r'C:\Users\user\Desktop\btcyillik.csv', sep=',',index_col=0)
data

Şimdi    Açılış    Yüksek     Düşük     Hac.   Fark %
Tarih                                                               
13.05.2022  30.339,5  28.994,3  31.002,7  28.755,0  196,11K    4,71%
12.05.2022  28.976,0  29.073,4  30.136,7  26.500,5  309,48K   -0,32%
11.05.2022  29.068,2  31.008,0  32.113,6  27.835,5  296,90K   -6,25%
10.05.2022  31.007,5  30.098,2  32.621,2  29.831,0  235,61K    3,03%
09.05.2022  30.095,0  34.041,0  34.227,0  30.095,0  268,09K  -11,64%
...              ...       ...       ...       ...      ...      ...
17.05.2021  43.541,3  46.424,2  46.545,4  42.201,5  274,76K   -6,21%
16.05.2021  46.426,4  46.729,3  49.764,3  43.920,8  180,07K   -0,60%
15.05.2021  46.708,8  49.839,1  50.640,9  46.650,2  131,91K   -6,28%
14.05.2021  49.839,8  49.704,9  51.459,2  48.874,0  118,84K    0,27%
13.05.2021  49.704,6  49.398,2  51.337,3  46.331,1  236,71K    0,65%

[366 rows x 6 columns]

In [143]:
data.index = pd.to_datetime(data.index, format='%d.%m.%Y')

In [144]:
data.head(10)

Şimdi    Açılış    Yüksek     Düşük     Hac.   Fark %
Tarih                                                               
2022-05-13  30.339,5  28.994,3  31.002,7  28.755,0  196,11K    4,71%
2022-05-12  28.976,0  29.073,4  30.136,7  26.500,5  309,48K   -0,32%
2022-05-11  29.068,2  31.008,0  32.113,6  27.835,5  296,90K   -6,25%
2022-05-10  31.007,5  30.098,2  32.621,2  29.831,0  235,61K    3,03%
2022-05-09  30.095,0  34.041,0  34.227,0  30.095,0  268,09K  -11,64%
2022-05-08  34.060,0  35.468,0  35.497,0  33.727,0  671,05M   -3,97%
2022-05-07  35.468,0  36.003,0  36.119,0  34.773,0  288,86M   -1,50%
2022-05-06  36.009,0  36.540,0  36.646,0  35.267,0  752,84M   -1,46%
2022-05-05  36.544,0  39.686,0  39.833,0  36.183,0    1,04B   -7,92%
2022-05-04  39.688,0  37.717,0  40.021,0  37.660,0  691,49M    5,22%

In [145]:
dataf=data.replace('[^\d.]','',regex=True).astype(float)
dataf

Şimdi   Açılış   Yüksek    Düşük     Hac.  Fark %
Tarih                                                          
2022-05-13  30.3395  28.9943  31.0027  28.7550  19611.0   471.0
2022-05-12  28.9760  29.0734  30.1367  26.5005  30948.0    32.0
2022-05-11  29.0682  31.0080  32.1136  27.8355  29690.0   625.0
2022-05-10  31.0075  30.0982  32.6212  29.8310  23561.0   303.0
2022-05-09  30.0950  34.0410  34.2270  30.0950  26809.0  1164.0
...             ...      ...      ...      ...      ...     ...
2021-05-17  43.5413  46.4242  46.5454  42.2015  27476.0   621.0
2021-05-16  46.4264  46.7293  49.7643  43.9208  18007.0    60.0
2021-05-15  46.7088  49.8391  50.6409  46.6502  13191.0   628.0
2021-05-14  49.8398  49.7049  51.4592  48.8740  11884.0    27.0
2021-05-13  49.7046  49.3982  51.3373  46.3311  23671.0    65.0

[366 rows x 6 columns]

In [146]:
dataf_shifted = dataf.iloc[:10,:]
dataf_shifted

Şimdi   Açılış   Yüksek    Düşük     Hac.  Fark %
Tarih                                                          
2022-05-13  30.3395  28.9943  31.0027  28.7550  19611.0   471.0
2022-05-12  28.9760  29.0734  30.1367  26.5005  30948.0    32.0
2022-05-11  29.0682  31.0080  32.1136  27.8355  29690.0   625.0
2022-05-10  31.0075  30.0982  32.6212  29.8310  23561.0   303.0
2022-05-09  30.0950  34.0410  34.2270  30.0950  26809.0  1164.0
2022-05-08  34.0600  35.4680  35.4970  33.7270  67105.0   397.0
2022-05-07  35.4680  36.0030  36.1190  34.7730  28886.0   150.0
2022-05-06  36.0090  36.5400  36.6460  35.2670  75284.0   146.0
2022-05-05  36.5440  39.6860  39.8330  36.1830    104.0   792.0
2022-05-04  39.6880  37.7170  40.0210  37.6600  69149.0   522.0

In [147]:
scaler = MinMaxScaler()
dataf_scaled=scaler.fit_transform(dataf_shifted.values)
dataf_scaled=pd.DataFrame(dataf_scaled, columns=data.columns)
dataf_scaled.index=dataf_shifted.index
dataf_scaled.head()

Şimdi    Açılış    Yüksek     Düşük      Hac.    Fark %
Tarih                                                                 
2022-05-13  0.127287  0.000000  0.087614  0.202025  0.259471  0.387809
2022-05-12  0.000000  0.007398  0.000000  0.000000  0.410269  0.000000
2022-05-11  0.008607  0.188342  0.200004  0.119629  0.393536  0.523852
2022-05-10  0.189647  0.103248  0.251358  0.298445  0.312011  0.239399
2022-05-09  0.104462  0.472020  0.413818  0.322102  0.355214  1.000000

In [148]:
scaler = MinMaxScaler()
dataf_scaled=scaler.fit_transform(dataf_shifted.values)
dataf_scaled=pd.DataFrame(dataf_scaled, columns=data.columns)
dataf_scaled.index=dataf_shifted.index
dataf_scaled.head()

Şimdi    Açılış    Yüksek     Düşük      Hac.    Fark %
Tarih                                                                 
2022-05-13  0.127287  0.000000  0.087614  0.202025  0.259471  0.387809
2022-05-12  0.000000  0.007398  0.000000  0.000000  0.410269  0.000000
2022-05-11  0.008607  0.188342  0.200004  0.119629  0.393536  0.523852
2022-05-10  0.189647  0.103248  0.251358  0.298445  0.312011  0.239399
2022-05-09  0.104462  0.472020  0.413818  0.322102  0.355214  1.000000

In [149]:
scaler = MinMaxScaler()
dataf_scaled=scaler.fit_transform(dataf_shifted.values)
dataf_scaled=pd.DataFrame(dataf_scaled, columns=data.columns)
dataf_scaled.index=dataf_shifted.index
dataf_scaled.head(10)

Şimdi    Açılış    Yüksek     Düşük      Hac.    Fark %
Tarih                                                                 
2022-05-13  0.127287  0.000000  0.087614  0.202025  0.259471  0.387809
2022-05-12  0.000000  0.007398  0.000000  0.000000  0.410269  0.000000
2022-05-11  0.008607  0.188342  0.200004  0.119629  0.393536  0.523852
2022-05-10  0.189647  0.103248  0.251358  0.298445  0.312011  0.239399
2022-05-09  0.104462  0.472020  0.413818  0.322102  0.355214  1.000000
2022-05-08  0.474608  0.605488  0.542304  0.647565  0.891208  0.322438
2022-05-07  0.606049  0.655527  0.605233  0.741297  0.382841  0.104240
2022-05-06  0.656553  0.705753  0.658549  0.785564  1.000000  0.100707
2022-05-05  0.706497  1.000000  0.980980  0.867646  0.000000  0.671378
2022-05-04  1.000000  0.815838  1.000000  1.000000  0.918396  0.432862

In [150]:
x1=dataf_scaled.iloc[:,[1]]
x2=dataf_scaled.iloc[:,[0]]
y=dataf_scaled.iloc[:,[2]]


In [151]:
x1

Açılış
Tarih               
2022-05-13  0.000000
2022-05-12  0.007398
2022-05-11  0.188342
2022-05-10  0.103248
2022-05-09  0.472020
2022-05-08  0.605488
2022-05-07  0.655527
2022-05-06  0.705753
2022-05-05  1.000000
2022-05-04  0.815838

In [152]:
w11=0.5
w21=0.5
w12=1
w22=1
b1=1
b2=0.75
W1=-1
W2=1
M=0.5
#1.iterasyon
net1=x1.values[0]*w11+x2.values[0]*w21

fnet1=1/(1+(1/(2.71828**(net1+b1))))

net2=x1.values[0]*w12+x2.values[0]*w22

fnet2=1/(1+(1/(2.71828**(net2+b1))))

net3=fnet1*W1+fnet2*W2
fnet3=1/(1+(1/(2.71828**(net3+b2))))

hata = y.values[0]-fnet3
    
hata

array([-0.59416351])

In [153]:
w11=w11-(M*x1.values[0]*hata)
w12=w12-(M*x1.values[0]*hata)
w21=w21-(M*x2.values[0]*hata)
w22=w22-(M*x2.values[0]*hata)
W1=W1-(M*fnet1*hata)
W2=W2-(M*fnet2*hata)
w11,w12,w21,w22,W1,W2

(array([0.5]),
 array([1.]),
 array([0.53781469]),
 array([1.03781469]),
 array([-0.77915356]),
 array([1.22439707]))

In [154]:
#2.iterasyon
net1=x1.values[1]*w11+x2.values[1]*w21

fnet1=1/(1+(1/(2.71828**(net1+b1))))

net2=x1.values[1]*w12+x2.values[1]*w22

fnet2=1/(1+(1/(2.71828**(net2+b1))))

net3=fnet1*W1+fnet2*W2
fnet3=1/(1+(1/(2.71828**(net3+b2))))

hata1 = y.values[1]-fnet3

hata1

array([-0.74587089])

In [155]:
w11=w11-(M*x1.values[1]*hata1)
w12=w12-(M*x1.values[1]*hata1)
w21=w21-(M*x2.values[1]*hata1)
w22=w22-(M*x2.values[1]*hata1)
W1=W1-(M*fnet1*hata1)
W2=W2-(M*fnet2*hata1)
w11,w12,w21,w22,W1,W2

(array([0.50275907]),
 array([1.00275907]),
 array([0.53781469]),
 array([1.03781469]),
 array([-0.50624495]),
 array([1.49757622]))

In [156]:
#3.iterasyon
net1=x1.values[2]*w11+x2.values[2]*w21

fnet1=1/(1+(1/(2.71828**(net1+b1))))

net2=x1.values[2]*w12+x2.values[2]*w22

fnet2=1/(1+(1/(2.71828**(net2+b1))))

net3=fnet1*W1+fnet2*W2
fnet3=1/(1+(1/(2.71828**(net3+b2))))

hata2 = y.values[2]-fnet3

hata2

array([-0.62062049])

In [157]:
w11=w11-(M*x1.values[2]*hata2)
w12=w12-(M*x1.values[2]*hata2)
w21=w21-(M*x2.values[2]*hata2)
w22=w22-(M*x2.values[2]*hata2)
W1=W1-(M*fnet1*hata2)
W2=W2-(M*fnet2*hata2)
w11,w12,w21,w22,W1,W2

(array([0.56120364]),
 array([1.06120364]),
 array([0.54048558]),
 array([1.04048558]),
 array([-0.27347114]),
 array([1.73593547]))

In [158]:
#4.iterasyon
net1=x1.values[3]*w11+x2.values[3]*w21

fnet1=1/(1+(1/(2.71828**(net1+b1))))

net2=x1.values[3]*w12+x2.values[3]*w22

fnet2=1/(1+(1/(2.71828**(net2+b1))))

net3=fnet1*W1+fnet2*W2
fnet3=1/(1+(1/(2.71828**(net3+b2))))

hata3 = y.values[3]-fnet3

hata3

array([-0.6194296])

In [159]:
w11=w11-(M*x1.values[3]*hata3)
w12=w12-(M*x1.values[3]*hata3)
w21=w21-(M*x2.values[3]*hata3)
w22=w22-(M*x2.values[3]*hata3)
W1=W1-(M*fnet1*hata3)
W2=W2-(M*fnet2*hata3)
w11,w12,w21,w22,W1,W2

(array([0.59318117]),
 array([1.09318117]),
 array([0.59922211]),
 array([1.09922211]),
 array([-0.03765015]),
 array([1.97967872]))

In [160]:
#5.iterasyon
net1=x1.values[4]*w11+x2.values[4]*w21

fnet1=1/(1+(1/(2.71828**(net1+b1))))

net2=x1.values[4]*w12+x2.values[4]*w22

fnet2=1/(1+(1/(2.71828**(net2+b1))))

net3=fnet1*W1+fnet2*W2
fnet3=1/(1+(1/(2.71828**(net3+b2))))

hata4 = y.values[4]-fnet3

hata4

array([-0.50113891])

In [161]:
w11=w11-(M*x1.values[4]*hata4)
w12=w12-(M*x1.values[4]*hata4)
w21=w21-(M*x2.values[4]*hata4)
w22=w22-(M*x2.values[4]*hata4)
W1=W1-(M*fnet1*hata4)
W2=W2-(M*fnet2*hata4)
w11,w12,w21,w22,W1,W2

(array([0.71145505]),
 array([1.21145505]),
 array([0.62539716]),
 array([1.12539716]),
 array([0.16103022]),
 array([2.18922577]))

In [162]:
#6.iterasyon
net1=x1.values[5]*w11+x2.values[5]*w21

fnet1=1/(1+(1/(2.71828**(net1+b1))))

net2=x1.values[5]*w12+x2.values[5]*w22

fnet2=1/(1+(1/(2.71828**(net2+b1))))

net3=fnet1*W1+fnet2*W2
fnet3=1/(1+(1/(2.71828**(net3+b2))))

hata5 = y.values[5]-fnet3

hata5

array([-0.40406537])

In [163]:
w11=w11-(M*x1.values[5]*hata5)
w12=w12-(M*x1.values[5]*hata5)
w21=w21-(M*x2.values[5]*hata5)
w22=w22-(M*x2.values[5]*hata5)
W1=W1-(M*fnet1*hata5)
W2=W2-(M*fnet2*hata5)
w11,w12,w21,w22,W1,W2

(array([0.83378349]),
 array([1.33378349]),
 array([0.72128348]),
 array([1.22128348]),
 array([0.33257709]),
 array([2.37230002]))

In [164]:
#7. iterasyon
net1=x1.values[6]*w11+x2.values[6]*w21

fnet1=1/(1+(1/(2.71828**(net1+b1))))

net2=x1.values[6]*w12+x2.values[6]*w22

fnet2=1/(1+(1/(2.71828**(net2+b1))))

net3=fnet1*W1+fnet2*W2
fnet3=1/(1+(1/(2.71828**(net3+b2))))

hata6 = y.values[6]-fnet3

hata6

array([-0.35754246])

In [165]:
w11=w11-(M*x1.values[6]*hata6)
w12=w12-(M*x1.values[6]*hata6)
w21=w21-(M*x2.values[6]*hata6)
w22=w22-(M*x2.values[6]*hata6)
W1=W1-(M*fnet1*hata6)
W2=W2-(M*fnet2*hata6)
w11,w12,w21,w22,W1,W2

(array([0.95097289]),
 array([1.45097289]),
 array([0.82962765]),
 array([1.32962765]),
 array([0.48973041]),
 array([2.53887693]))

In [166]:
#8. iterasyon
net1=x1.values[7]*w11+x2.values[7]*w21

fnet1=1/(1+(1/(2.71828**(net1+b1))))

net2=x1.values[7]*w12+x2.values[7]*w22

fnet2=1/(1+(1/(2.71828**(net2+b1))))

net3=fnet1*W1+fnet2*W2
fnet3=1/(1+(1/(2.71828**(net3+b2))))

hata7 = y.values[7]-fnet3

hata7

array([-0.31479288])

In [167]:
w11=w11-(M*x1.values[7]*hata7)
w12=w12-(M*x1.values[7]*hata7)
w21=w21-(M*x2.values[7]*hata7)
w22=w22-(M*x2.values[7]*hata7)
W1=W1-(M*fnet1*hata7)
W2=W2-(M*fnet2*hata7)
w11,w12,w21,w22,W1,W2

(array([1.06205591]),
 array([1.56205591]),
 array([0.93296682]),
 array([1.43296682]),
 array([0.63164903]),
 array([2.6880412]))

In [170]:
#9.iterasyon
net1=x1.values[8]*w11+x2.values[8]*w21

fnet1=1/(1+(1/(2.71828**(net1+b1))))

net2=x1.values[8]*w12+x2.values[8]*w22

fnet2=1/(1+(1/(2.71828**(net2+b1))))

net3=fnet1*W1+fnet2*W2
fnet3=1/(1+(1/(2.71828**(net3+b2))))

hata8 = y.values[8]-fnet3

fnet3

array([0.98124568])

In [169]:
hata,hata1,hata2,hata3,hata4,hata5,hata6,hata7,hata8

(array([-0.59416351]),
 array([-0.74587089]),
 array([-0.62062049]),
 array([-0.6194296]),
 array([-0.50113891]),
 array([-0.40406537]),
 array([-0.35754246]),
 array([-0.31479288]),
 array([-0.00026575]))

(array([0.00130715]), array([0.6817772]))